- test/kubernetes/address_test.go
Response for pods disabled should be `NXDOMAIN` not `SERVFAIL`, per README and per unit tests.
Fixing the expected value here first... will correct the code next.
> Fix expected response for pods disabled

- build/kubernetes/dns-test.yaml
- test/kubernetes/ptr_test.go
Adds tests for k8s PTR requests, covering namespace exposure, existing/non-existing IPs, for services and endpoints. (#5)
> add k8s ptr tests

- test/kubernetes/ptr_test.go
Adds PTR test for IPv6 endpoint.
coredns/coredns#1236
> k8s: test PTR for IPv6 endpoints

- Makefile
- build/pr-comment-hook.sh
- test/k8sdeployment/deployment_test.go
- test/kubernetes/tools.go
Adds kubernetes deployment script tests...
- deploy manifest with `coredns/deployment/kubernetes/deploy.sh`
- verify coredns starts
- check queries to verify reverse zones, and basic functionality
- scrape metrics to verify prometheus is exposed 
these will be triggered by `/integration` in a comment of a coredns/deployment PR, in the same way as in coredns/coredns.
example output:
```
=== RUN   TestKubernetesDeployment
=== RUN   TestKubernetesDeployment/Deploy_with_deploy.sh
=== RUN   TestKubernetesDeployment/Verify_coredns_starts
=== RUN   TestKubernetesDeployment/Verify_metrics_available
=== RUN   TestKubernetesDeployment/svc-1-a.test-1.svc.cluster.local._A
=== RUN   TestKubernetesDeployment/10-20-0-101.test-1.pod.cluster.local._A
=== RUN …
```
> Add kubernetes deployment script tests

- test/k8sdeployment/deployment_test.go
Add health check.  This essentially verifies that health port is exposed, and that the pods becomes healthy before continuing other tests.
> kubernetes: add health check test

- test/k8sdeployment/deployment_test.go
- test/kubernetes/tools.go
WaitReady assumed to always wait for 2 pods, and we only launch one pod in coredns integration tests. Added WaitNReady(), and fixes to wait for only 1 pod in coredns repo integration tests, and for 2 in the deployment tests.
> kubernetes: Fix WaitReady

- README.md
- build/pr-comment-hook.sh
Integration test status is now posted to the via the commit status API, instead of via comments.
This presents itself as an additional check in the "Checks" section of a PR (along side travis, if travis is doing CI in the repo).  
Like this ...
> kubernetes: Use status instead of comments

- test/kubernetes/excluster_test.go
Test was broken by backward incompatible Corefile format change in coredns/coredns#1453.
> kubernetes: remove commas from external cluster test

- build/pr-comment-hook.sh
In addition to PR "synchronize" events, also process PR "open" events.
Fixes: #33
> Also process PR "open" events

- test/kubernetes/upstream_test.go
Add 2 upstream tests:
- bare `upstream` to self
- `upstream X` to another server
Do not merge until coredns/coredns#1484 merges.
> kubernetes: upstream test

- build/kubernetes/dns-test.yaml
- test/kubernetes/upstream_test.go
Create a CNAME chain loop, and make sure a query to it doesn't recurse forever.
> kubernetes: upstream loop limit check

- Makefile
don't go get before building, because it can fail if upstream libraries are in a broken state on master.
> kubernetes: dont go get

- build/kubernetes/coredns.yaml
- test/kubernetes/tools.go
Change label to kube-dns to prevent break in CI test after change in coredns manifest in https://github.com/coredns/deployment/pull/69
> Fix failures due to k8s-app label change

- build/kubernetes/coredns.yaml
- build/kubernetes/dns-test.yaml
- build/kubernetes/minikube_install.sh
- build/kubernetes/minikube_setup.sh
- build/kubernetes/minikube_teardown.sh
- test/k8sdeployment/deployment_test.go
- test/kubernetai/address_test.go
- test/kubernetai/autopath_test.go
- test/kubernetes/address_test.go
- test/kubernetes/autopath_test.go
- test/kubernetes/excluster_test.go
- test/kubernetes/nsexposure_test.go
- test/kubernetes/ptr_test.go
- test/kubernetes/srv_test.go
- test/kubernetes/tools.go
- test/kubernetes/tools_test.go
Update minikube to latest.
Update to k8s 1.10...
minikube changes:
1. CIDR range is now 10.96.0.0/25 (test cases updated to reflect this)
2. kubeadm is now used by minikube instead of localkube (some adjustments reqd)
> Update minikube + k8s

- test/kubernetes/excluster_test.go
endpoint URL changes required after upgrade to latest minikube 0.27.0.
> update k8s endpoint urls for ext-cluster tests

- test/kubernetes/upstream_test.go
In the upstream CNAME loop break test, tolerate duplicate answer records created by template plugin.
> Tolerate dups from template plugin

- test/kubernetai/autopath_test.go
Avoid nil ref in case of error during test.
> Avoid nil ref during test

- test/k8sdeployment/configmap_test.go
- test/k8sdeployment/deployment_test.go
- test/kubernetes/tools.go
Test the deploy script part which handles the ConfigMap translation from kube-dns to CoreDNS
> Add tests for configmap translation

- test/kubernetes/address_test.go
Add tests that...
* add a new service and endpoints objects after CoreDNS is started
* verify that CoreDNS responds with records for those objects.
> kubernetes: Add new objects test

- build/kubernetes/minikube_teardown.sh
New version of `kubeadm` interactively asks if you are sure when doing a `kubeadm reset` (even when scripted), passing `-f` forces reset without "are you sure".
> force kubeadm reset

- test/kubernetes/tools.go
Address test failed in https://drone.coredns.io/log/view.html?pr=4b3a6e2df87e963f9be170143e7a6609b1fa2971 which built in https://github.com/coredns/coredns/pull/2508 .
> Move TempFile to plugin test

- build/kubernetes/minikube_install.sh
- build/kubernetes/minikube_setup.sh
Updates Minikube version to v0.33.1 - We no longer need to be bothered by the addon manager since DNS is removed from there.
Updates Kubernetes to v1.13.3
> Update Minikube and Kubernetes version

- test/k8sdeployment/connection_test.go
- test/kubernetes/tools.go
Adds test to ensure coredns does not crash when the apiserver is restarted. 
This test validates https://github.com/coredns/deployment/pull/138 and catch issues like https://github.com/coredns/coredns/issues/2464
> Add test to check connection to the apiserver

- test/k8sdeployment/configmap_test.go
- test/k8sdeployment/deployment_test.go
- Remove the kube-dns ConfigMap after testing translation using deploy script.
- Remove `-s` option for cases in https://github.com/coredns/deployment/pull/144 where it's more common to have no kube-dns configmap.
/cc @chrisohaver
> Cleanup deployment test

- test/kubernetai/autopath_test.go
The proxy plugin was removed from CoreDNS; use forward plugin instead.
> kubernetai tests: proxy removed, use forward

- .circleci/config.yml
- README.md
Enables running CoreDNS benchmark tests on CircleCI
Tested that it successfully runs on https://github.com/rajansandeep/ci/pull/1
> Add benchmarks tests

- test/k8sdeployment/deployment_test.go
report fatal error if we get a nil response so failed tests don't cause go test to panic
> check for nil response

- test/k8sdeployment/connection_test.go
- test/k8sdeployment/deployment_test.go
Modifications for expecting new default deployment of a single CoreDNS replica.
> test/deployment: expect 1 replica

- test/k8sdeployment/configmap_test.go
- test/k8sdeployment/deployment_test.go
Removes 2 tests that assume  "pod" subdomain records are configured and present.
See: coredns/deployment#209
> Adapt tests for removal of "pod" subdomain records

- test/kubernetes/address_test.go
Update the test TestKubernetesA/dns-version.cluster.local._TXT
with the new schema version
Signed-off-by: Antonio Ojea <antonio.ojea.garcia@gmail.com>
xref: https://github.com/coredns/coredns/pull/3554
> Bump k8s DNS schema version to 1.1.0

- test/kubernetes/address_test.go
- test/kubernetes/fallthrough_test.go
- test/kubernetes/srv_test.go
Signed-off-by: Zou Nengren <zouyee1989@gmail.com>
**notes for reviewer:**
```
Also re-enabled and adjusted the kubernetes upstream behavior test to verify default upstream 
behavior. The test had been commented out when the upstream option was originally deprecated.
```
> remove kubernetes related option

- test/k8sdeployment/configmap_test.go
Updates test to accommodate https://github.com/coredns/deployment/pull/233
> Add max_concurrent option to configmap test

- build/kubernetes/k8s_setup.sh
- test/k8sdeployment/connection_test.go
- test/k8sdeployment/deployment_test.go
- test/kubernetes/tools.go
Some tests were skipped due to them incompatible with the way `kind` works.
Refactored the tests for them to be working on the `kind` cluster.
> Fix and re-enable skipped tests

- .circleci/config.yml
The Kubernetes tests will now run against 3 versions of k8s.
Needed to update to v2.1 and refactor to accommodate running the tests in parallel
> Have Kubernetes tests run for previous versions of k8s

- go.mod
- test/k8sdeployment/deployment_test.go
- test/kubernetes/metrics_test.go
- test/kubernetes/tools.go
This adds e2e tests for the `coredns_kubernetes_dns_programming_duration_seconds` metric.
It is expected to fail as is, since the metric is not currently functional in CoreDNS.
So, probably hold off on merging this until the bug is fixed in CoreDNS (e.g. as in coredns/coredns#4255).
> Add e2e test for dns programming latency metric

- build/kubernetes/dns-test.yaml
- test/kubernetes/address_test.go
Adds a headless service and deployment with pods that never download an image, so that they stay perpetually unready.
Adds a test that verifies a query for the headless service selecting the unready pods will return nxdomain.
> kubernetes: Add test for unready endpoints

- test/kubernetes/srv_test.go
One wildcard SRV test flakes occasionally. I cannot reproduce the failure locally.  Seems to be some oddity with the test environment. Removing.
Closes #140
> Remove flaking test

- build/kubernetes/dns-test.yaml
- test/kubernetes/endpoints_test.go
Adds a test for `endpoint_pod_names`.
Includes a test for a long pod name exceeding valid DNS label length.
> kubernetes: add endpoint_pod_names test

- test/kubernetai/axfr_test.go
- test/kubernetes/axfr_test.go
- test/kubernetes/tools.go
This PR builds upon https://github.com/coredns/ci/pull/157 to add kubernetai AXFR integration tests.
The kubernetai tests should fail until AXFR is properly supported in the plugin:
```
=== RUN   TestAXFR
=== RUN   TestAXFR/matches_stanza_1/test-4.svc.cluster.local._AXFR
axfr_test.go:187: expected 1 query attempt, observed 0
axfr_test.go:196: coredns log: .:53
CoreDNS-1.11.3
linux/arm64, go1.23.1, ce45312
[INFO] 172.17.0.1:37727 - 13103 "AXFR IN test-4.svc.cluster.local. tcp 65 false 65535" - - 0 0.000046625s
=== RUN   TestAXFR/matches_stanza_2/test-5.svc.cluster.local._AXFR
axfr_test.go:187: expected 1 query attempt, observed 0
axfr_test.go:196: coredns log: .:53
CoreDNS-1.11.3
linux/arm64, go1.23.1, ce45312
[INFO] 172.17.0.1:36319 - 63827 "AXFR IN test-5.svc.cluster.local. tcp 65 false …
```
> Add kubernetai axfr tests

- test/k8sdeployment/deployment_test.go
- test/kubernetai/address_test.go
- test/kubernetai/axfr_test.go
- test/kubernetes/address_test.go
- test/kubernetes/autopath_test.go
- test/kubernetes/axfr_test.go
- test/kubernetes/endpoints_test.go
- test/kubernetes/fallthrough_test.go
- test/kubernetes/nsexposure_test.go
- test/kubernetes/pods_test.go
- test/kubernetes/ptr_test.go
- test/kubernetes/srv_test.go
- test/kubernetes/tools.go
- test/metadata_edns0/metadata_edns0_test.go
fix format string funcs with missing format strings.
ALSO (UNRELATED)... remove test cases from the default k8s coredns config deployment tests that depend on external dns servers.  Two test cases relied on getting responses from upstream dns servers - one referring to example.net, which now returns 4 A records instead of 1.  Rather than update the test expectation to 4, I'm just removing these since they are kludgey.
> fix unused format string funcs
