coredns/ci

- test/kubernetes/address_test.go
> Add expected auth section for podsdisabled

- test/k8sdeployment/deployment_test.go
Update call to deploy.sh with flagged parameters
> k8sdeployment: update script call

- build/pr-comment-hook.sh
- test/k8sdeployment/deployment_test.go
- test/kubernetes/tools.go
health check code again - testing out new option to integration test...
> kubernetes: health check

- build/pr-comment-hook.sh
Handle pull request events.  Will run integration tests when PR is opened, and when new commits are pushed to a PR.
> kubernetes: Add pull_request webhook

- Makefile
mimic the mode of PR fetching from Travis, which i think pulls a head-merged version of the PR.
> kubernetes: fetch merged pr for test

- build/pr-comment-hook.sh
- test/kubernetes/excluster_test.go
> WIP kubernetes: Extend CoreDNS external to cluster tests

- build/pr-comment-hook.sh
> kubernetes: only trigger test on commit sync

- build/kubernetes/minikube_setup.sh
- build/view.html
- remove k8s version check error.
- ignore errors from add-on manager (minikube bug?)
- don't refresh log content of it hasn't changed
Related:
#36
coredns/coredns#1491
> kubernetes: clean up log a bit

- Makefile
- build/kubernetes/minikube_setup.sh
- build/view.html
Display log with collapsible sections.
Add link to raw log.
> Display log with collapsible sections

- build/view.html
When following the tail of the log, collapse as sections as they complete.
> collapse as sections complete when following

- test/kubernetes/ptr_test.go
Fixes for coredns/coredns#1524
> kubernetes: fix ptr nxdomain responses

- build/view.html
also...
Highlight on mouse hover so it's more apparent they are clickable.
Also add a hint at bottom of log that you can expand sections by clicking.
> Colorize section headers

- build/view.html
better highlight `make` errors.
> kubernetes: Tweak error highlighting

- README.md
Add tips for getting the tests to run locally.
> Add tips for running tests locally

- build/kubernetes/minikube_setup.sh
- test/kubernetes/federation_test.go
Do not merge until coredns/coredns#2177 is merged
> Add k8s federation test

- build/kubernetes/coredns.yaml
- build/kubernetes/minikube_setup.sh
- test/kubernetes/tools.go
* fix log output when coredns has failed
* add permission to get nodes in api
> test adjustments/fixes

- Makefile
... so people dont have to hunt for them
> add links to ci test repo

- test/kubernetai/autopath_test.go
Hello
Added a few test to fit the update of kubernetai autopath [here #16](https://github.com/coredns/kubernetai/pull/16)
> [kubernetai][autopath] - Add test for multicluster setup

- test/kubernetes/address_test.go
- test/kubernetes/fallthrough_test.go
- test/kubernetes/upstream_test.go
See https://github.com/coredns/coredns/pull/2436 for the CoreDNS
changes.
Signed-off-by: Miek Gieben <miek@miek.nl>
> Fix upstream test

- test/kubernetes/excluster_test.go
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
> Enable api fallthrough test

- test/metadata_edns0/metadata_edns0_test.go
Try to get the logs again from coredns if it fails. 
Error out if logs cannot be retrieved to make sure we can pinpoint where the test is failing.
> Add log check to metadata_edns0 test

- Makefile
- go.mod
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
> Enable go mod

- test/k8sdeployment/configmap_test.go
Still hard-coded. 
Will get around to making a better solution.
> Fix translation test for v1.5.0

- test/kubernetes/tools.go
See https://github.com/coredns/coredns/issues/2959
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
> Update Caddy's import path

- test/k8sdeployment/configmap_test.go
Signed-off-by: Sandeep Rajan <srajan@infoblox.com>
> Add lameduck option to configmap test

- test/k8sdeployment/deployment_test.go
Split deployment test into separate tests so we can see partial failures.
> Split up deployment tests

- test/k8sdeployment/configmap_test.go
- test/kubernetes/tools.go
Makes changes to configmap test made in https://github.com/coredns/deployment/pull/229
> update deployment tests to remove federation support

- go.mod
- test/kubernetes/tools.go
This makes the moves and adds a tiny bit of cleanups.
> Move to coredns/caddy

- test/k8sdeployment/deployment_test.go
As suggested in https://github.com/coredns/ci/pull/129#discussion_r497654513, adding a separate test for checking ready
> Add test for checking readiness

- test/kubernetes/metrics_test.go
Skip Endpoints tests (but still do EndpointSlices tests) for k8s >= 1.19 with following code comment:
```
// Skip tests for Endpoints if we are monitoring EndpointSlices (>= k8s 1.19).
// Endpoint should be copied to EndpointSlices via the K8s EndpointSliceMirror
// Controller. However, it may be unpredictably slow in the CI VMs and result
// in flaky testing, or slow tests if we wait for it to complete.  We are already testing
// EndpointSlices directly, so there is little value to testing Endpoints here.
```
When testing on my laptop, the 1 second sleep was sufficient time to allow the endpointslicemirror controller to do its work.  But it seems that this isn't the case in the CI.  As in the comment, we are already testing EndpointSlices directly, so there is negligible value in testing …
> skip endpoints tests >= 1.19

- .circleci/config.yml
- test/kubernetes/metrics_test.go
> Update k8s versions in CI

- test/kubernetes/address_test.go
> Add NS query test case to kubernetes tests

- .circleci/config.yml
> Only run benchmark tests in benchmark job

- test/kubernetai/autopath_test.go
- test/kubernetes/autopath_test.go
- test/kubernetes/fallthrough_test.go
- test/kubernetes/reload_test.go
- test/kubernetes/tools.go
> Add reload test

- build/kubernetes/dns-test.yaml
- test/kubernetes/ptr_test.go
> Revert "Adjust PTR tests and endpoint test fixtures to match new PTR behavior"

- test/kubernetes/metrics_test.go
Fix prometheus update caused by CI failure.
See 
- https://github.com/coredns/coredns/pull/7522
- https://github.com/coredns/coredns/pull/7533
> Fix prometheus update
